# Generated by Django 4.2.7 on 2024-02-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="content_type",
            field=models.CharField(
                help_text="The MIMEType of the file", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="picture",
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
